apiVersion: v1
kind: Pod
metadata:
  name: mailsense
spec:
  containers:
    - name: postgres
      image: localhost/mailsense-postgres:18
      env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: mailsense
      ports:
        - containerPort: 5432
          hostPort: 5432
          hostIP: 127.0.0.1
      volumeMounts:
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: init-scripts
      hostPath:
        path: ./scripts
        type: Directory
    - name: postgres-data
      hostPath:
        path: ./postgres-data
        type: DirectoryOrCreate
